#!/usr/bin/env python3
"""Generate `zira/fonts.css` with @font-face rules for the built Zira fonts.

Reads `private-build-plans.toml` for family/weight/slope metadata and scans
`zira/woff2` (and `zira/ttf`) for the built font files. The generated CSS
uses relative URLs, so it can be served from the repo root via any CDN, e.g.

    https://cdn.jsdelivr.net/gh/<user>/<repo>@main/zira/fonts.css

Run from anywhere; paths are resolved relative to this script.
"""

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOML_PATH = ROOT / "private-build-plans.toml"
OUT_PATH = ROOT / "zira" / "fonts.css"
WOFF2_DIR = ROOT / "zira" / "woff2"
TTF_DIR = ROOT / "zira" / "ttf"

# Iosevka's makeSuffix(): width/weight/slope names, where "Normal"/"Regular"/
# "Upright" are omitted and an empty result falls back to "Regular".
SLOPE_SUFFIX = {"Upright": "", "Italic": "Italic", "Oblique": "Oblique"}


def build_suffix_map(weight_names, slope_names):
    """Map a file suffix (e.g. 'BoldItalic') to (weight_name, slope_name)."""
    mapping = {}
    default_weight = weight_names[0] if weight_names else "Regular"
    for wn in weight_names:
        for sn in slope_names:
            suf = SLOPE_SUFFIX.get(sn, sn)
            if wn == "Regular" and suf:
                # Iosevka omits the Regular weight when a slope is present
                mapping.setdefault(suf, (wn, sn))
            mapping[wn + suf] = (wn, sn)
    mapping.setdefault("", (default_weight, slope_names[0] if slope_names else "Upright"))
    return mapping


def main():
    try:
        with open(TOML_PATH, "rb") as f:
            data = tomllib.load(f)
    except FileNotFoundError:
        print(f"ERROR: {TOML_PATH} not found", file=sys.stderr)
        return 1

    plans = data.get("buildPlans", {})
    if not plans:
        print("ERROR: no [buildPlans.*] found in private-build-plans.toml", file=sys.stderr)
        return 1

    rules = []
    for plan_name, plan in plans.items():
        family = plan.get("family", plan_name)
        weights = plan.get("weights", {})
        slopes = plan.get("slopes", {})
        if not weights or not slopes:
            print(f"WARN: plan '{plan_name}' has no weights/slopes; skipping", file=sys.stderr)
            continue

        suffix_map = build_suffix_map(list(weights.keys()), list(slopes.keys()))
        font_files = sorted(WOFF2_DIR.glob(f"{plan_name}-*.woff2"))
        for woff2_file in font_files:
            suffix = woff2_file.stem[len(plan_name) + 1 :]
            key = suffix_map.get(suffix)
            if key is None:
                print(f"WARN: cannot parse style suffix '{suffix}' of {woff2_file.name}; skipping",
                      file=sys.stderr)
                continue
            weight_name, slope_name = key
            css_weight = weights[weight_name].get("css", 400)
            css_style = slopes[slope_name].get("css", "normal")

            srcs = [f"url('woff2/{woff2_file.name}') format('woff2')"]
            ttf_file = TTF_DIR / f"{woff2_file.stem}.ttf"
            if ttf_file.exists():
                srcs.append(f"url('ttf/{ttf_file.name}') format('truetype')")

            rules.append(
                "@font-face {\n"
                f"\tfont-family: '{family}';\n"
                f"\tfont-style: {css_style};\n"
                f"\tfont-weight: {css_weight};\n"
                "\tfont-display: swap;\n"
                f"\tsrc: {', '.join(srcs)};\n"
                "}"
            )

    if not rules:
        print("ERROR: no fonts found in zira/woff2; nothing to generate", file=sys.stderr)
        return 1

    header = "/* Generated by tools/make-webfont-css.py - do not edit by hand. */\n"
    OUT_PATH.write_text(header + "\n".join(rules) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH} with {len(rules)} @font-face rules.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
